name: "ubuntu bash fuzzing CI workflow"


on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month  


jobs:

     

  ubuntu-latest-radamsa-job:
    name: "radamsa on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status    
    - name: "deploy radamsa"
      run: sudo make deploy-radamsa
